name: dependabot-auto-merge

on:
  pull_request_target:
    types: [opened, reopened, synchronize, ready_for_review]

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' && !github.event.pull_request.draft }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v3.0.0
        with:
          github-token: ${{ github.token }}

      - name: Enable auto-merge for patch and minor updates
        if: ${{ contains(fromJson('["version-update:semver-patch","version-update:semver-minor"]'), steps.metadata.outputs.update-type) }}
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh pr merge --auto --squash "${{ github.event.pull_request.html_url }}"
